// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma-postgres/schema.prisma",
  migrations: {
    path: "prisma-postgres/migrations",
  },
  datasource: {
    url: env("POSTGRES_URL"),
  },
});
